In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4, 5])
print(type(a))
print(a)

b = np.array([[10, 20, 30], [60, 70, 80]])
print(b)

print(b.ndim)
print(b.shape)

<class 'numpy.ndarray'>
[1 2 3 4 5]
[[10 20 30]
 [60 70 80]]
2
(2, 3)


In [5]:
a = np.zeros((2,3))
print(a)

a = np.ones((2,3))
print(a)

a = np.full((2,2),7)
print(a)

a = np.eye(3)
print(a)

a = np.random.random((2,2))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.93361681 0.94082662]
 [0.60949011 0.15643929]]


In [7]:
a = np.arange(10)
print(a)

a = np.arange(1, 10, 2)
print(a)

a = np.array(np.arange(30)).reshape((5,6))
print(a)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [9]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a[0:2, 0:2]
print(b)

[[1 2]
 [4 5]]


In [10]:
b = a[0, :]
print(b)

[1 2 3]


In [11]:
b = a[:, 1]
print(b)

[2 5]


In [13]:
a = np.array([[1,2], [4,5], [7,8]])
print(a)
b = a[[2,1], [1,0]]
print(b)

[[1 2]
 [4 5]
 [7 8]]
[8 4]
